apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ucp-plan-documents
  namespace: {OSE_PROJECT}
  selfLink: /oapi/v1/namespaces/{OSE_PROJECT}/deploymentconfigs/ucp-plan-documents
  uid: bd0fd512-4577-11e7-a210-005056a40b64
  resourceVersion: '137475604'
  creationTimestamp: '2017-05-30T20:37:03Z'
  labels:
    app: ucp-plan-documents
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
      resources: {  }
  triggers:
    -
      type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: ucp-plan-documents
    deploymentconfig: ucp-plan-documents
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ucp-plan-documents
        deploymentconfig: ucp-plan-documents
      annotations:
        openshift.io/container.ucp-plan-documents.image.entrypoint: '["/opt/webserver/bin/launch.sh"]'
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        -
          name: ucp-plan-documents
          image: 'docker.repo1.uhc.com/consumer_portals/ucp-plan-documents:ucp-plan-documents-{PIPELINE_VERSION}-{GIT_BRANCH}'
          ports:
            -
              containerPort: 8080
              protocol: TCP
            -
              containerPort: 8443
              protocol: TCP
            -
              containerPort: 8778
              protocol: TCP
          env:
            -
              name: env
              value: {OSE_PROJECT}
            -
              name: JAVA_OPTS_APPEND
              value: " -Djavax.net.ssl.trustStore=/portal/conf/ucp-plan-documents/repo/.openshift/config/truststore.jks -Djavax.net.ssl.trustStorePassword=sslpassword "
            -
              name: MYSQL_USER
              value: admin
            -
              name: MYSQL_PASSWORD
              value: admin
            -
              name: MYSQL_DATABASE
              value: mnr
          resources: {  }
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {  }
status:
  latestVersion: {BUILD_NUMBER}
  details:
    causes:
      -
        type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            name: 'ucp-plan-documents-{PIPELINE_VERSION}-{GIT_BRANCH}'
